{
 "title": "Metric Daemon",
 "description": "Metric daemon monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Metrics Processed Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  'Metrics Processed' as name,\n  value\nFROM\n  metric_table_general\nWHERE\n  $__timeFilter(time)\n  and name = 'md.srv.metricsProcessed'\n"
    }
   ]
  },
  {
   "title": "Metrics Errors Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  'Metrics Processed' as name,\n  value\nFROM\n  metric_table_general\nWHERE\n  $__timeFilter(time)\n  and name = 'md.srv.metricErrors'\n"
    }
   ]
  },
  {
   "title": "Metric Database Write Errors Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  'Metrics Processed' as name,\n  value\nFROM\n  metric_table_general\nWHERE\n  $__timeFilter(time)\n  and name = 'md.db.metricProcessingErrors'\n"
    }
   ]
  },
  {
   "title": "Invalid Indexed Metrics Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  'Metrics Processed' as name,\n  value\nFROM\n  metric_table_general\nWHERE\n  $__timeFilter(time)\n  and name = 'md.db.invalidIndexedMetrics'\n"
    }
   ]
  }
 ]
}